data <- read.table("./data/household_power_consumption.txt",sep=";",skip=66637, nrows=69517-66637, colClasses = c("character","character",rep("numeric",7)))
header <- read.table("./data/household_power_consumption.txt",sep=";",nrows = 1, stringsAsFactors = FALSE)
colnames(data) <- header
png("plot3.png")
par(mar=c(4,4,3,2))
palette = c("black", "#ff2500", "#0433ff")
plot(range(1:nrow(data)), c(min(data$Sub_metering_1,data$Sub_metering_2,data$Sub_metering_3),max(data$Sub_metering_1,data$Sub_metering_2,data$Sub_metering_3)), type="n", xaxt="n", ylab="Energy sub metering", xlab="")
lines(1:nrow(data),data$Sub_metering_1,col=palette[1])
lines(1:nrow(data),data$Sub_metering_2,col=palette[2])
lines(1:nrow(data),data$Sub_metering_3,col=palette[3])
axis(side=1, at=c(0,match(2,as.numeric(format(strptime(data$Date, format="%d/%m/%Y"), "%d"))), nrow(data)), labels = c("Thu","Fri","Sat"))
legend("topright", lwd=rep(1,3), col = palette, legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()